// 09-ts-react/lecture/NumberBaseball.tsx
import * as React from 'react';
import { useRef, useState } from 'react';
import Try from './Try';
import { TryInfo } from './Types';

const getNumbers = () => {
    const candidates = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    const array = [];
    for (let i = 0; i < 4; i += 1) {
        const chosen = candidates.splice(Math.floor(Math.random() * (9 - i)), 1)[0];
        array.push(chosen);
    }
    return array;
};

const NumberBaseball = () => {
    const [answer, setAnswer] = useState(getNumbers());
    const [value, setValue] = useState('');
    const [result, setResult] = useState('');
    const [tries, setTries] = useState<TryInfo[]>([]);
    const inputEl = useRef<HTMLInputElement | null>(null);

    const onSubmitForm = (e: React.FormEvent) => {
        e.preventDefault();
        const input = inputEl.current;
        if (value === answer.join('')) {
            setTries((t) => ([
                ...t,
                {
                    try: value,
                    result: '홈런!',
                },
            ]));
            setResult('홈런!');
            alert('게임을 다시 실행합니다.');
            setValue('');
            setAnswer(getNumbers());
            setTries([]);
            if (input) {
                input.focus();
            }
        } else {
            const answerArray = value.split('').map((v) => parseInt(v));
            let strike = 0;
            let ball = 0;
            if (tries.length >= 9) {
                setResult(`10번 넘게 틀려서 실패! 답은 ${answer.join(',')}였습니다!`); // state set은 비동기
                alert('게임을 다시 시작합니다.');
                setValue('');
                setAnswer(getNumbers());
                setTries([]);
                if (input) {
                    input.focus();
                }
            } else {
                console.log('답은', answer.join(''));
                for (let i = 0; i < 4; i += 1) {
                    if (answerArray[i] === answer[i]) {
                        console.log('strike', answerArray[i], answer[i]);
                        strike += 1;
                    } else if (answer.includes(answerArray[i])) {
                        console.log('ball', answerArray[i], answer.indexOf(answerArray[i]));
                        ball += 1;
                    }
                }
                setTries(t => ([
                    ...t,
                    {
                        try: value,
                        result: `${strike} 스트라이크, ${ball} 볼입니다.`,
                    },
                ]));
                setValue('');
                if (input) {
                    input.focus();
                }
            }
        }
    };

    return (
        <>
            <h1>{result}</h1>
            <form onSubmit={onSubmitForm}>
                <input
                    ref={inputEl}
                    maxLength={4}
                    value={value}
                    onChange={(e) => setValue(e.target.value)}
                />
                <button>입력!</button>
            </form>
            <div>시도: {tries.length}</div>
            <ul>
                {tries.map((v, i) => (
                    <Try key={`${i + 1}차 시도 : ${v.try}`} tryInfo={v} />
                ))}
            </ul>
        </>
    );
};

export default NumberBaseball;

// 07-VueJs/03-vuejs-숫자야구/NumberBaseball.vue
<template>
<div>
    <h1>{{result}}</h1>
    <form @submit.prevent="onSubmitform"> <!-- v-on: => @ 로 대체가능 //.prevent => e.prevent.default 자동적용  -->
    <input ref="answer" minlength="4" maxlength="4" v-model="value">
    <button>입력</button>
    </form>
    <div>시도 : {{tries.length}}</div>
    <ul>
        <li v-for="t in tries">
        <div>{{t.try}}</div>
        <div>{{t.result}}</div>
        </li>
    </ul>
</div>
</template>

<script>
  const getNumbers = () => {
    const candidates = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    const array = [];
    for (let i = 0; i < 4; i += 1) {
      const chosen = candidates.splice(Math.floor(Math.random() * (9 - i)), 1)[0];
      array.push(chosen);
    }
    return array;
  };

    export default {
        data(){
           return{
        answer: getNumbers(), // ex) [1,5,3,4]
        tries: [], // 시도 수
        value: '', // 입력
        result: '', // 결과
      }
    },
        methods: {
            onSubmitform(){
                if( this.value === this.answer.join('')){ // 정답 맞췄으면
                this.tries.push({
                    try : this.value,
                    result : '홈런',
                });
                this.result = '홈런';
                alert('게임을 다시 실행합니다.')
                this.value = '';
                this.tries = [];
                this.$refs.answer.focus();
                } else { // 틀렸을 경우
          if (this.tries.length >= 9) { // 10번째 시도
            this.result = `10번 넘게 틀려서 실패! 답은 ${this.answer.join(',')}였습니다!`;
            alert('게임을 다시 시작합니다.');
            this.value = '';
            this.answer = getNumbers();
            this.tries = [];
            this.$refs.answer.focus();
          }
                  let strike = 0;
                  let ball = 0;
                  const answerArry = this.value.split('').map(v => parseInt(v)); // 문자열을 숫자로 바꾸는 코드
                  console.log(this.answer)
                  for(let i = 0 ; i < 4; i ++){
                      if(answerArry[i] === this.answer[i]){ // 자리수 까지 맞았을 경우
                    strike++;
                    }else if(this.answer.includes(answerArry[i])){ // 숫자만 정답
                    ball++;
                    }
                  }
                  this.tries.push({
                      try : this.value,
                      result : `${strike} 스크라이크 , ${ball} 볼 입니다.`
                  });
                this.value = '';
                this.$refs.answer.focus();
                }
            },
        },
    };
</script>

<style>

</style>
